spring.application.name=StudyCode

spring.datasource.url=jdbc:postgresql://localhost:5432/studytracker
spring.datasource.username=postgres
spring.datasource.password=131025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
